<?php

/**
 * Implements hook_form_alter
 */
function asb_scheme_form_alter(&$form, &$form_state, $form_id) {
  // Check if the form has steps and add progress markup.
  if(!empty($form['#steps'])) {
    // TODO: May want to add settings to include images
    // to the progress markup.
    $output = '<div id="step-wapper" style="display:block;height:16px;">';
    foreach($form['#steps'] as $step_name => $step) {
      if($form_state['storage']['step'] == $step_name) {
        // TODO: Remove inline styling.
        $output .= '<span class="step-progress-current" ';
        $output .= 'style="display:inline-block;background:red;width:16px;height:16px;';
        $output .= 'margin:0 .2em;border-radius:10px;">';
        $output .= '</span>';
      }else{
        $output .= '<span class="step-progress" ';
        $output .= 'style="display:inline-block;background:blue;width:16px;height:16px;';
        $output .= 'margin:0 .2em;border-radius:10px;">';
        $output .= '</span>';
      }
    }
  $output .= '</div>';
  $form['progress'] = array(
    '#markup' => $output,
    '#weight' => 150,
  );
  }
}
